### ISSUE TITLE
"ERROR: dial tcp: i/o timeout"

### ISSUE THREAD

**Issue by flickerfly** [kasimon/docker-heartbleed#2]
I'm getting "ERROR: dial tcp: i/o timeout" on most, but not all requests through this docker. It fails on ones I know to be good and some I know to be bad tests.

I'm running docker with sudo at this point.

    $ sudo docker run me/heartbleed some.com:443
2014/04/09 15:54:43 some.com:443 - ERROR: dial tcp: i/o timeout

    $ sudo docker version
    Client version: 0.10.0
    Client API version: 1.10
    Go version (client): go1.2.1
    Git commit (client): dc9c28f
    Server version: 0.10.0
    Server API version: 1.10
    Git commit (server): dc9c28f
    Go version (server): go1.2.1
    Last stable version: 0.10.0

    $ uname -a
    Linux Jules 3.11.0-18-generic #32-Ubuntu SMP Tue Feb 18 21:11:14 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

   $ grep dns /etc/default/docker 
   DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"

So what's causing the error and how do I mitigate it? Sorry if it's a simple answer. This is my first docker exposure.

**Comment by jchiu85** [comment]
Leave a comment

**Comment by deegees78** [comment]
@flickerfly, have you tried this behind firewall or without firewall?
I got really irritated with this error and then I worked with my network team. and sorted out.
for me the timeout error was for different ips at different time.

**Comment by flickerfly** [comment]
I've long since stopped checking specifically for heartbleed. I'll go ahead and close this.
